### ISSUE TITLE
Time Scheduler

### ISSUE THREAD

**Issue by Mowenyii** [ChenyangQiQi/FateZero#9]
I run the command: 
```
CUDA_VISIBLE_DEVICES=0 python test_fatezero.py --config config/teaser/jeep_watercolor.yaml 
```

Found at https://github.com/ChenyangQiQi/FateZero/blob/main/video_diffusion/pipelines/p2pDDIMSpatioTemporalPipeline.py#L155    self.scheduler.config.num_train_timesteps is 1000, self.scheduler.num_inference_steps is 50, timestep is 1. 

After line 155, timestep=-19, next_timestep=1. May I ask why is it designed that way?

**Comment by ChenyangQiQi** [comment]
For "self.scheduler.num_inference_steps=50 <   self.scheduler.config.num_train_timesteps = 1000", it is because the Unet is training using DDPM pipeline with timestep 1000, while it can be accelerated with DDIM pipeline using 50 steps. 

You may check the original paper https://arxiv.org/abs/2010.02502 and DDIM inversion code from Null-text inversion https://github.com/google/prompt-to-prompt/blob/main/null_text_w_ptp.ipynb


I guess you are check the initial value of timestep at 155.
next_timestep=1 is the initilization of first timestep in DDIM, which is 1.
After timestep

**Comment by Mowenyii** [comment]
Thank you very much！
